name: MongoDB CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  mongodb-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build mongodb

      # Tag Docker Image
      - name: Tag Docker Image
        run: docker tag mongodb zhongqianchen/wbm:mongodb

      # Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push zhongqianchen/wbm:mongodb
