name: MongoDB CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build MongoDB Docker container
      - name: Build MongoDB
        run: docker-compose -f docker-compose.yml build mongodb

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker-compose -f docker-compose.yml push mongodb
      
      # Deploy MongoDB to Digital Ocean
      - name: Deploy MongoDB to Digital Ocean
        run: |
          ssh root@${{ secrets.DROPLET_IP_ADDRESS }} "echo ${DROPLET_PASSWORD} | sudo -S bash -s" < deploy.sh
        env:
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
