name: Web App CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  webapp-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      # Install dependencies
      - name: Install dependencies
        working-directory: web-app
        run: pip install -r requirements.txt
          
      # Run tests
      - name: Run tests
        working-directory: web-app
        run: |
          coverage run -m pytest
          coverage report -m
          
      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build Docker image
      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build webapp

      # Tag Docker Image
      - name: Tag Docker Image
        run: docker tag webapp zhongqianchen/wbm:webapp

      # Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push zhongqianchen/wbm:webapp

      # SCP Files to Digital Ocean Droplet
      - name: SCP Files to Digital Ocean Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP_ADDRESS }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          timeout: 120s
          source: "mongodb,web-app,docker-compose.yml"
          target: '/var/www/webapp'
          
      # SSH into Digital Ocean Droplet and Run Docker Compose
      - name: SSH into Digital Ocean Droplet and Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP_ADDRESS }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            cd /var/www/webapp
            docker stop mongodb || true
            docker rm mongodb || true
            docker compose up --build
