name: Web App CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      # Install dependencies
      - name: Install dependencies
        working-directory: web-app
        run: pip install -r requirements.txt
          
      # Run tests
      - name: Run tests
        working-directory: web-app
        run: |
          coverage run -m pytest
          coverage report -m
          
      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build Docker image
      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build webapp
        
      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker-compose -f docker-compose.yml push webapp
        
      # Deploy to Digital Ocean
      - name: Deploy Web App to Digital Ocean
        run: |
          ssh root@${{ secrets.DROPLET_IP_ADDRESS }} "echo ${DROPLET_PASSWORD} | sudo -S bash -s" < deploy.sh
        env:
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
