name: Web App CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      # Install dependencies
      - name: Install dependencies
        working-directory: web-app  # Set the working directory to the web-app folder
        run: pip install -r requirements.txt
          
      # Run tests
      #- name: Run tests
      #  working-directory: web-app
      #  run: pytest --cov=web-app test-app.py
          
      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build Docker image
      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build webapp
        
      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker-compose -f docker-compose.yml push webapp
        
      # Deploy to Digital Ocean
      - name: Deploy Web App to Digital Ocean
        working-directory: web-app
        run: |
          # Install doctl
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.60.0/doctl-1.60.0-linux-amd64.tar.gz | tar -xzv
          sudo mv ./doctl /usr/local/bin/doctl
          doctl version
          
          # Authenticate with Digital Ocean using token
          doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
          # Deploy web application using Docker Compose
          doctl apps create --spec web-app/doctl-manifest.yml
